# Assessment-1:

Input_table.csv contains lot number with various runs. we need a output with lot numbers with runs in the column. Attaching both Input and Output File.

In [1]:
import pandas as pd

In [2]:
Data_set1 = pd.read_csv("Assignment1_Input_table.csv")
Data_set1.head()

,Entry Order,lot_number,group,panel,analyst,watson_id,assay_date,Plate Order Number,Run,Comments for Mean Response Without Drug,with_drug_response,Comments for Mean Response With Drug,inhibition_percent
0,1,HMN32540,D,2,SDS,13,30/07/20 0:00,1,122.5,,136.0,,-11.020408
1,2,HMN32538,D,2,SDS,13,30/07/20 0:00,1,136.5,,155.5,,-13.919414
2,3,HMN32549,D,2,SDS,13,30/07/20 0:00,1,142.5,,149.0,,-4.561404
3,4,HMN32537,D,2,SDS,13,30/07/20 0:00,1,101.5,,110.5,,-8.866995
4,5,HMN32551,D,2,SDS,13,30/07/20 0:00,1,144.5,,160.5,,-11.072664

In [26]:
Data_set2 = pd.read_csv('Assignment1_Output_table.csv')
Data_set2.head()

  Group     Sample  Run 1  Run 2  Run 3  Run 4  Run 5  Run 6
0     B  HMN193206   80.5  119.5   99.5  113.0   97.5   79.5
1     B  HMN193214   82.0   92.0   80.5   98.0   84.0   76.5
2     A  HMN193215   82.5  102.5   76.5  108.5   74.0   77.5
3     B  HMN193222   79.0   96.5   75.5  103.5   86.0   79.0
4     B  HMN193223   84.5  148.0  106.5  129.5  101.0   85.5

In [37]:
D1 = Data_set1.iloc[:,[1]]
D1

    lot_number
0     HMN32540
1     HMN32538
2     HMN32549
3     HMN32537
4     HMN32551
..         ...
295   HMN32537
296   HMN32551
297   HMN32545
298   HMN32554
299   HMN32531

[300 rows x 1 columns]

In [38]:
D2 = Data_set2.iloc[:,range(2,8)]
D2

    Run 1  Run 2  Run 3  Run 4  Run 5  Run 6
0    80.5  119.5   99.5  113.0   97.5   79.5
1    82.0   92.0   80.5   98.0   84.0   76.5
2    82.5  102.5   76.5  108.5   74.0   77.5
3    79.0   96.5   75.5  103.5   86.0   79.0
4    84.5  148.0  106.5  129.5  101.0   85.5
5    98.0  155.5  109.5  182.5  127.0  112.0
6    92.5  140.0  105.0  111.0   99.5   85.0
7    72.5   82.5   71.0   77.5   63.5   71.5
8   100.5  120.5   68.0  102.5   83.5   95.0
9    76.5   98.0   72.0   88.5   68.5   78.0
10   95.0  101.5   94.5   93.0   87.0   81.5
11   87.5  136.5   88.0   99.5   87.0   85.5
12   93.0  122.5  126.0   89.0   86.0   86.5
13   90.0  137.0   86.0  107.0   90.0   87.0
14   85.5  117.5   91.5   99.0   77.5   86.5
15  106.0  151.5  104.5  115.5   96.0   90.0
16   89.0  136.5  112.5  115.0   86.5   90.0
17   84.5   94.5   82.5   94.0   83.5   86.0
18   94.5  142.5  106.0  104.0   84.5   92.5
19   90.5  151.0   87.0  118.5   95.5   88.5
20  102.0  144.5  105.5  119.5  102.0   93.5
21   99.5  133.0   98.0  101.0   89.5   86.5
22   90.0  114.5   82.0   99.0   88.5   83.5
23   90.5  136.0   83.5  106.0   83.0   84.5
24   77.5  119.5  102.0   99.0   84.5   89.5
25   79.5  116.0  101.5  103.0   84.5   95.5
26   93.5  154.5  112.5  127.0  105.0   94.0
27   73.0  102.0   88.5   95.5   84.0   82.5
28   81.0  136.0   94.0  123.0   98.0   95.5
29   86.5  119.5  107.0  107.0   91.5   89.5
30   80.0  129.0  110.5  126.5   92.0   87.5
31   82.0  106.0  107.0   93.0   89.0   79.0
32   74.5   94.0   83.5   96.0   80.5   71.0
33   91.0  157.0   91.5  144.5   87.0   83.5
34   79.0  124.5  100.5  133.5  119.0   79.5
35   73.0  104.0   86.5   97.0   83.0   75.0
36   80.5  138.5   89.5  116.5   91.0   93.0
37   71.5   92.5  105.0   97.5   78.5   75.5
38   79.0  109.5   73.5   98.0   76.5   84.5
39   78.0  105.0   79.5   96.5   74.0   80.0
40   78.5  115.0   82.5  107.0   84.0   82.5
41   89.0   92.5   84.5   99.0   81.5   74.5
42   85.0  158.0   75.0  126.0  106.0  122.0
43   92.5  130.5  108.5  104.5   92.5   98.0
44   70.5   89.0  108.0   90.0   73.0   75.0
45   85.5  118.0   73.5  107.5  103.0   84.5
46   77.0  145.5   94.0  126.0   94.5   80.5
47   78.0  108.0  101.0   97.5   82.5   81.0
48   85.5  161.5  122.5  136.5  105.5   99.0
49   76.0   94.0   86.0   96.5   78.5   77.0

In [60]:
attach = D2.assign(lot_number=D1)
attach

    Run 1  Run 2  Run 3  Run 4  Run 5  Run 6 lot_number
0    80.5  119.5   99.5  113.0   97.5   79.5   HMN32540
1    82.0   92.0   80.5   98.0   84.0   76.5   HMN32538
2    82.5  102.5   76.5  108.5   74.0   77.5   HMN32549
3    79.0   96.5   75.5  103.5   86.0   79.0   HMN32537
4    84.5  148.0  106.5  129.5  101.0   85.5   HMN32551
5    98.0  155.5  109.5  182.5  127.0  112.0   HMN32545
6    92.5  140.0  105.0  111.0   99.5   85.0   HMN32554
7    72.5   82.5   71.0   77.5   63.5   71.5   HMN32531
8   100.5  120.5   68.0  102.5   83.5   95.0  HMN366249
9    76.5   98.0   72.0   88.5   68.5   78.0  HMN366338
10   95.0  101.5   94.5   93.0   87.0   81.5  HMN366384
11   87.5  136.5   88.0   99.5   87.0   85.5  HMN366342
12   93.0  122.5  126.0   89.0   86.0   86.5  HMN366250
13   90.0  137.0   86.0  107.0   90.0   87.0  HMN364398
14   85.5  117.5   91.5   99.0   77.5   86.5  HMN364358
15  106.0  151.5  104.5  115.5   96.0   90.0  HMN364386
16   89.0  136.5  112.5  115.0   86.5   90.0  HMN364347
17   84.5   94.5   82.5   94.0   83.5   86.0  HMN364338
18   94.5  142.5  106.0  104.0   84.5   92.5  HMN364390
19   90.5  151.0   87.0  118.5   95.5   88.5  HMN364405
20  102.0  144.5  105.5  119.5  102.0   93.5  HMN634397
21   99.5  133.0   98.0  101.0   89.5   86.5   HMN32546
22   90.0  114.5   82.0   99.0   88.5   83.5  HMN193214
23   90.5  136.0   83.5  106.0   83.0   84.5  HMN193225
24   77.5  119.5  102.0   99.0   84.5   89.5  HMN193222
25   79.5  116.0  101.5  103.0   84.5   95.5  HMN193206
26   93.5  154.5  112.5  127.0  105.0   94.0    HMNXXXX
27   73.0  102.0   88.5   95.5   84.0   82.5  HMN193232
28   81.0  136.0   94.0  123.0   98.0   95.5  HMN193223
29   86.5  119.5  107.0  107.0   91.5   89.5  HMN366251
30   80.0  129.0  110.5  126.5   92.0   87.5  HMN366203
31   82.0  106.0  107.0   93.0   89.0   79.0  HMN366343
32   74.5   94.0   83.5   96.0   80.5   71.0  HMN366246
33   91.0  157.0   91.5  144.5   87.0   83.5  HMN366348
34   79.0  124.5  100.5  133.5  119.0   79.5  HMN366194
35   73.0  104.0   86.5   97.0   83.0   75.0  HMN366390
36   80.5  138.5   89.5  116.5   91.0   93.0   HMN32543
37   71.5   92.5  105.0   97.5   78.5   75.5   HMN32535
38   79.0  109.5   73.5   98.0   76.5   84.5   HMN32530
39   78.0  105.0   79.5   96.5   74.0   80.0   HMN32550
40   78.5  115.0   82.5  107.0   84.0   82.5   HMN32547
41   89.0   92.5   84.5   99.0   81.5   74.5   HMN32542
42   85.0  158.0   75.0  126.0  106.0  122.0  HMN362212
43   92.5  130.5  108.5  104.5   92.5   98.0  HMN362213
44   70.5   89.0  108.0   90.0   73.0   75.0  HMN366293
45   85.5  118.0   73.5  107.5  103.0   84.5  HMN366301
46   77.0  145.5   94.0  126.0   94.5   80.5  HMN366300
47   78.0  108.0  101.0   97.5   82.5   81.0  HMN366302
48   85.5  161.5  122.5  136.5  105.5   99.0  HMN366211
49   76.0   94.0   86.0   96.5   78.5   77.0  HMN193215

# Assessment-2:

Word document contains a table which is basically two table that needs to be split and saved in two different csv files. attaching input and output file.

In [65]:
!pip install python-docx

Collecting python-docx
  Downloading python-docx-0.8.11.tar.gz (5.6 MB)
Requirement already satisfied: lxml>=2.3.2 in f:\anacondapy\lib\site-packages (from python-docx) (4.8.0)
Building wheels for collected packages: python-docx
  Building wheel for python-docx (setup.py): started
  Building wheel for python-docx (setup.py): finished with status 'done'
  Created wheel for python-docx: filename=python_docx-0.8.11-py3-none-any.whl size=184507 sha256=a8407775c2ec8f85874a4ef7e7a171618eb7988d2037748aaea99e40562617de
  Stored in directory: c:\users\aryan\appdata\local\pip\cache\wheels\83\8b\7c\09ae60c42c7ba4ed2dddaf2b8b9186cb105255856d6ed3dba5
Successfully built python-docx
Installing collected packages: python-docx
Successfully installed python-docx-0.8.11

# Assignment-3 (Time Series Analysis)

Input File: ( long_data_.csv, dataset_tk.csv )

Content

(Data is in the form of a time series for a period of 17 months beginning from 2nd Jan 2019 till 23rd May 2020.
Rows are indexed with dates and columns represent states.
Rows and columns put together, each datapoint reflects the power consumed in Mega Units (MU) by the given state (column) at the given date (row).)

 

Write a program with Time Series Analysis to build a prediction model for next 1 Day for Power Consumption for each state.
if we place the file in our system and run your code without any changes, it should execute and give the output